# NOTE: Rename this file without the '_example' suffix to allow loading

# NOTE: These are only used when the module doesn't receive them via HTTP already (e.g. from game)
serverIP	= example.ddns.net
serverPort	= 27015

# Path to server cfg file with the rcon_password setting (at the beginning)
rconPassFile = "/path/to/rcon_password.cfg"
